const express = require('express');
const router = express.Router();
const categoryController = require('../controllers/categoryController');
const uploadMiddleware = require('../middlewares/uploadMiddleware');

// Create a new category
router.post('/', categoryController.createCategory);

// Get all categories
router.get('/', categoryController.getAllCategories);

// Get a single category by ID
router.get('/:categoryId', categoryController.getCategoryById);

// Update a category by ID
router.put('/:categoryId', categoryController.updateCategory);

// Delete a category by ID
router.delete('/:categoryId', categoryController.deleteCategory);

// Search categories by either title or type
router.get('/search', categoryController.searchCategories);

// Handle file upload
router.post('/upload', uploadMiddleware.single('file'), (req, res) => {
    try {
        // Check if a file was uploaded
        if (!req.file) {
            return res.status(400).json({ message: 'No file uploaded' });
        }

        // Access the unique ID generated by the middleware
        const uniqueId = req.uploadedFileId;

        // You can now use `uniqueId` to store it in your database or generate the URL as needed

        // Respond with a success message
        res.status(200).json({ message: 'File uploaded successfully', fileId: uniqueId });
    } catch (error) {
        console.error('Error uploading file:', error);
        res.status(500).json({ message: 'Error uploading file' });
    }
});

module.exports = router;